codecov:
  require_ci_to_pass: no
  token: ead56467-56da-4804-9663-57752cf5edde

coverage:
  precision: 2
  round: down
  range: "50...80"
ignore:
  - */tests/.*
  - */Item.java
  - */Message.java
  - */OngoingTask.java
  - */PurchaseRecord.java
  - */Store.java
  - */User.java
  - *.yml
  - *.db
  - *.xml


comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no
