spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: b4fe2812c8c4c9eb9474
            clientSecret: noo
          google:
            client-id: 401429020966-on22e8ci574tuseh711o94vburf8krmc.apps.googleusercontent.com
            client-secret: NOO