spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: b4fe2812c8c4c9eb9474
            clientSecret: e464c8e1b6fd0658a6d766a8baf57468ac5d4b3d
          google:
            client-id: 567161309655-rp7k5ndpu716t21gg6tts7c7b23ddrat.apps.googleusercontent.com
            client-secret: w-p7x2HQtAkurfMdIp3spr15
