spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: b4fe2812c8c4c9eb9474
            clientSecret: e464c8e1b6fd0658a6d766a8baf57468ac5d4b3d
          google:
            client-id: 401429020966-oj3571jtlioqu3ofkqd69fkrbcaml776.apps.googleusercontent.com
            client-secret: v3BIBYPki_wTZ15oZzsRbx-i