spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: b4fe2812c8c4c9eb9474
            clientSecret: here
          google:
            client-id: 401429020966-oj3571jtlioqu3ofkqd69fkrbcaml776.apps.googleusercontent.com
            client-secret: here